apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: notification
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: notify
      interval: 30s