apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: auth
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 30s