apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gateway

  namespaceSelector:
    matchNames:
      - default

  endpoints:
  - port: http  #SericeMonitor sees the port name, not the port number
    path: /metrics
    interval: 15s